/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#b3093f',
        'error': '#ba1a1a',
        'surface-variant': '#e3e2e0',
        'on-background': '#1a1c1b',
        'on-primary-fixed': '#3f0012',
        'surface-bright': '#faf9f7',
        'background': '#faf9f7',
        'surface-container': '#efeeec',
        'tertiary-container': '#1b4e34',
        'surface-container-lowest': '#ffffff',
        'primary': '#b3093f',
        'tertiary-fixed': '#b8efcc',
        'on-primary-fixed-variant': '#8f002f',
        'on-tertiary-fixed': '#002111',
        'secondary-container': '#fcedc4',
        'on-secondary-container': '#634b00',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#1d5036',
        'secondary': '#775a00',
        'outline': '#897173',
        'inverse-primary': '#ffb1c4',
        'on-surface': '#1a1c1b',
        'tertiary-fixed-dim': '#9dd3b0',
        'primary-fixed': '#ffd9e2',
        'secondary-fixed-dim': '#f3dea0',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'primary-container': '#8f002f',
        'inverse-surface': '#2f3130',
        'on-surface-variant': '#564243',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'on-tertiary-container': '#8abe9d',
        'tertiary': '#003720',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e9e8e6',
        'surface-dim': '#dadad8',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#ffb1c4',
        'on-secondary-fixed': '#251a00',
        'surface-container-highest': '#e3e2e0',
        'secondary-fixed': '#fcedc4',
        'surface': '#faf9f7',
        'inverse-on-surface': '#f1f1ef',
        'surface-container-low': '#f4f3f1',
        'outline-variant': '#f4d8de',
        'on-secondary-fixed-variant': '#5a4300'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'spacing-xxs': '0.25rem',
        'spacing-lg': '1.5rem',
        'spacing-sm': '0.75rem',
        'gutter-mobile': '1rem',
        'spacing-md': '1rem',
        'spacing-xs': '0.5rem',
        'spacing-2xl': '3rem',
        'spacing-xl': '2rem',
        'gutter-tablet': '1.5rem',
        'margin-screen': '1.25rem'
      },
      fontFamily: {
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Source Serif 4"', 'serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Source Serif 4"', 'serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Source Serif 4"', 'serif'],
        'headline-lg-mobile': ['"Source Serif 4"', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif']
      },
      fontSize: {
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'title-md': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm': ['19px', { lineHeight: '26px', fontWeight: '600' }],
        'label-lg': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }]
      }
    }
  },
  plugins: []
};
